# Supabase configuration file
project_id = "rnahdxukfyzifvsbhndu"

[functions.ai-tutor]
verify_jwt = false

[functions.generate-parent-report-ai]
verify_jwt = false

[functions.get-parent-report]
verify_jwt = false

[functions.upload-pdf]
verify_jwt = false
